document.addEventListener('DOMContentLoaded', () => {
    const englishWords = [
        
            {english: "Hello", french: "Bonjour"},
            {english: "Goodbye", french: "Au revoir"},
            {english: "Please", french: "S'il vous plaît"},
            {english: "Thank you", french: "Merci"},
            {english: "You're welcome", french: "De rien"},
            {english: "How are you?", french: "Comment allez-vous ?"},
            {english: "I'm fine", french: "Je vais bien"},
            {english: "What's your name?", french: "Comment vous appelez-vous ?"},
            {english: "Nice to meet you", french: "Enchanté(e)"},
            {english: "Excuse me", french: "Excusez-moi"},
            {english: "I'm sorry", french: "Je suis désolé(e)"},
            {english: "Good morning", french: "Bonjour (matin)"},
            {english: "Good evening", french: "Bonsoir"},
            {english: "Good night", french: "Bonne nuit"},
            {english: "See you later", french: "À plus tard"},
            {english: "Take care", french: "Prenez soin de vous"},
            {english: "Have a nice day", french: "Bonne journée"},
            {english: "I don't understand", french: "Je ne comprends pas"},
            {english: "Can you repeat that?", french: "Pouvez-vous répéter ?"},
            {english: "Do you speak English?", french: "Parlez-vous anglais ?"},
            {english: "I don't speak French", french: "Je ne parle pas français"},
            {english: "Where is...?", french: "Où est... ?"},
            {english: "How much?", french: "Combien ?"},
            {english: "I'd like...", french: "Je voudrais..."},
            {english: "Can you help me?", french: "Pouvez-vous m'aider ?"},
            {english: "I'm lost", french: "Je suis perdu(e)"},
            {english: "What time is it?", french: "Quelle heure est-il ?"},
            {english: "Today", french: "Aujourd'hui"},
            {english: "Tomorrow", french: "Demain"},
            {english: "Yesterday", french: "Hier"},
            {english: "Now", french: "Maintenant"},
            {english: "Later", french: "Plus tard"},
            {english: "Always", french: "Toujours"},
            {english: "Never", french: "Jamais"},
            {english: "Sometimes", french: "Parfois"},
            {english: "Often", french: "Souvent"},
            {english: "Rarely", french: "Rarement"},
            {english: "Happy", french: "Heureux"},
            {english: "Sad", french: "Triste"},
            {english: "Angry", french: "En colère"},
            {english: "Tired", french: "Fatigué"},
            {english: "Hungry", french: "Affamé"},
            {english: "Thirsty", french: "Assoiffé"},
            {english: "Hot", french: "Chaud"},
            {english: "Cold", french: "Froid"},
            {english: "Big", french: "Grand"},
            {english: "Small", french: "Petit"},
            {english: "Fast", french: "Rapide"},
            {english: "Slow", french: "Lent"},
            {english: "Easy", french: "Facile"},
            {english: "Difficult", french: "Difficile"},
            {english: "Good", french: "Bon"},
            {english: "Bad", french: "Mauvais"},
            {english: "Beautiful", french: "Beau"},
            {english: "Ugly", french: "Laid"},
            {english: "New", french: "Nouveau"},
            {english: "Old", french: "Vieux"},
            {english: "Young", french: "Jeune"},
            {english: "Rich", french: "Riche"},
            {english: "Poor", french: "Pauvre"},
            {english: "Strong", french: "Fort"},
            {english: "Weak", french: "Faible"},
            {english: "Loud", french: "Bruyant"},
            {english: "Quiet", french: "Calme"},
            {english: "Clean", french: "Propre"},
            {english: "Dirty", french: "Sale"},
            {english: "Open", french: "Ouvert"},
            {english: "Closed", french: "Fermé"},
            {english: "Full", french: "Plein"},
            {english: "Empty", french: "Vide"},
            {english: "True", french: "Vrai"},
            {english: "False", french: "Faux"},
            {english: "Right", french: "Droit"},
            {english: "Left", french: "Gauche"},
            {english: "Up", french: "En haut"},
            {english: "Down", french: "En bas"},
            {english: "Inside", french: "À l'intérieur"},
            {english: "Outside", french: "À l'extérieur"},
            {english: "Near", french: "Près"},
            {english: "Far", french: "Loin"},
            {english: "First", french: "Premier"},
            {english: "Last", french: "Dernier"},
            {english: "Before", french: "Avant"},
            {english: "After", french: "Après"},
            {english: "During", french: "Pendant"},
            {english: "While", french: "Tandis que"},
            {english: "Because", french: "Parce que"},
            {english: "If", french: "Si"},
            {english: "But", french: "Mais"},
            {english: "Or", french: "Ou"},
            {english: "And", french: "Et"},
            {english: "Also", french: "Aussi"},
            {english: "However", french: "Cependant"},
            {english: "Therefore", french: "Par conséquent"},
            {english: "Although", french: "Bien que"},
            {english: "Nevertheless", french: "Néanmoins"},
            {english: "Despite", french: "Malgré"},
            {english: "In spite of", french: "En dépit de"},
            {english: "According to", french: "Selon"},
            {english: "Regarding", french: "Concernant"},
            {english: "About", french: "À propos de"},
            {english: "Except", french: "Sauf"},
            {english: "Including", french: "Y compris"},
            {english: "Besides", french: "En outre"},
            {english: "Moreover", french: "De plus"},
            {english: "Furthermore", french: "En outre"},
            {english: "In addition", french: "En plus"},
            {english: "Consequently", french: "Par conséquent"},
            {english: "Thus", french: "Ainsi"},
            {english: "Hence", french: "Par conséquent"},
            {english: "Otherwise", french: "Sinon"},
            {english: "Rather", french: "Plutôt"},
            {english: "Instead", french: "Au lieu de"},
            {english: "Namely", french: "À savoir"},
            {english: "Specifically", french: "Spécifiquement"},
            {english: "For example", french: "Par exemple"},
            {english: "Such as", french: "Tel que"},
            {english: "Like", french: "Comme"},
            {english: "Unlike", french: "Contrairement à"},
            {english: "Compared to", french: "Comparé à"},
            {english: "Similarly", french: "De même"},
            {english: "Likewise", french: "Pareillement"},
            {english: "In contrast", french: "En revanche"},
            {english: "On the contrary", french: "Au contraire"},
            {english: "On the other hand", french: "D'autre part"},
            {english: "Conversely", french: "Inversement"},
            {english: "Meanwhile", french: "Pendant ce temps"},
            {english: "Subsequently", french: "Par la suite"},
            {english: "Eventually", french: "Finalement"},
            {english: "Ultimately", french: "En fin de compte"},
            {english: "Finally", french: "Enfin"},
            {english: "In conclusion", french: "En conclusion"},
            {english: "To sum up", french: "Pour résumer"},
            {english: "In summary", french: "En résumé"},
            {english: "Overall", french: "Dans l'ensemble"},
            {english: "Generally", french: "Généralement"},
            {english: "Typically", french: "Typiquement"},
            {english: "Usually", french: "Habituellement"},
            {english: "Occasionally", french: "Occasionnellement"},
            {english: "Frequently", french: "Fréquemment"},
            {english: "Seldom", french: "Rarement"},
            {english: "Hardly ever", french: "Presque jamais"},
            {english: "Barely", french: "À peine"},
            {english: "Scarcely", french: "À peine"},
            {english: "Almost", french: "Presque"},
            {english: "Nearly", french: "Presque"},
            {english: "Approximately", french: "Approximativement"},
            {english: "Roughly", french: "Grossièrement"},
            {english: "About", french: "Environ"},
            {english: "Around", french: "Autour de"},
            {english: "At least", french: "Au moins"},
            {english: "At most", french: "Au plus"},
            {english: "Up to", french: "Jusqu'à"},
            {english: "As much as", french: "Autant que"},
            {english: "As little as", french: "Aussi peu que"},
            {english: "More than", french: "Plus que"},
            {english: "Less than", french: "Moins que"},
            {english: "Equal to", french: "Égal à"},
            {english: "Equivalent to", french: "Équivalent à"},
            {english: "Similar to", french: "Similaire à"},
            {english: "Different from", french: "Différent de"},
            {english: "Opposite to", french: "Opposé à"},
            {english: "Contrary to", french: "Contrairement à"},
            {english: "Relative to", french: "Par rapport à"},
            {english: "In relation to", french: "En relation avec"},
            {english: "With respect to", french: "En ce qui concerne"},
            {english: "Regarding", french: "Concernant"},
            {english: "As for", french: "Quant à"},
            {english: "As to", french: "Quant à"},
            {english: "In terms of", french: "En termes de"},
            {english: "In the context of", french: "Dans le contexte de"},
            {english: "In light of", french: "À la lumière de"},
            {english: "Given", french: "Étant donné"},
            {english: "Provided that", french: "À condition que"},
            {english: "As long as", french: "Tant que"},
            {english: "So long as", french: "Tant que"},
            {english: "Unless", french: "À moins que"},
            {english: "Except if", french: "Sauf si"},
            {english: "Even if", french: "Même si"},
            {english: "Even though", french: "Bien que"},
            {english: "Although", french: "Bien que"},
            {english: "Whereas", french: "Tandis que"},
            {english: "While", french: "Alors que"},
            {english: "Since", french: "Puisque"},
            {english: "As", french: "Comme"},
            {english: "Because of", french: "À cause de"},
            {english: "Due to", french: "En raison de"},
            {english: "Owing to", french: "En raison de"},
            {english: "Thanks to", french: "Grâce à"},
            {english: "As a result of", french: "À la suite de"},
            {english: "Consequently", french: "Par conséquent"},
            {english: "Therefore", french: "Par conséquent"},
            {english: "Hence", french: "D'où"},
            {english: "Thus", french: "Ainsi"},
            {english: "So", french: "Donc"},
            {english: "Accordingly", french: "En conséquence"},
            {english: "As a consequence", french: "En conséquence"},
            {english: "For this reason", french: "Pour cette raison"},
            {english: "That's why", french: "C'est pourquoi"},
            {english: "This is why", french: "C'est pourquoi"},
            {english: "In order to", french: "Afin de"},
            {english: "So as to", french: "De manière à"},
            {english: "With the aim of", french: "Dans le but de"},
            {english: "For the purpose of", french: "Dans le but de"},
            {english: "With a view to", french: "En vue de"},
            {english: "In the hope of", french: "Dans l'espoir de"},
            {english: "Lest", french: "De peur que"},
            {english: "For fear of", french: "De peur de"},
            {english: "In case", french: "Au cas où"},
            {english: "In the event of", french: "En cas de"},
            {english: "Should", french: "Si jamais"},
            {english: "Were", french: "Si"},
            {english: "Had", french: "Si"},
            {english: "If only", french: "Si seulement"},
            {english: "I wish", french: "J'aimerais"},
            {english: "If I were you", french: "Si j'étais vous"},
            {english: "Suppose", french: "Supposons"},
            {english: "Assuming", french: "En supposant"},
            {english: "Granted", french: "Certes"},
            {english: "Admittedly", french: "Il faut admettre"},
            {english: "To be sure", french: "Il est vrai"},
            {english: "Undoubtedly", french: "Sans aucun doute"},
            {english: "Undeniably", french: "Indéniablement"},
            {english: "Unquestionably", french: "Sans conteste"},
            {english: "Beyond doubt", french: "Sans l'ombre d'un doute"},
            {english: "Needless to say", french: "Il va sans dire"},
            {english: "Naturally", french: "Naturellement"},
            {english: "Of course", french: "Bien sûr"},
            {english: "Certainly", french: "Certainement"},
            {english: "Surely", french: "Sûrement"},
            {english: "Indeed", french: "En effet"},
            {english: "In fact", french: "En fait"},
            {english: "Actually", french: "En réalité"},
            {english: "As a matter of fact", french: "En fait"},
            {english: "To tell the truth", french: "À vrai dire"},
            {english: "Frankly", french: "Franchement"},
            {english: "To be honest", french: "Pour être honnête"},
            {english: "In my opinion", french: "À mon avis"},
            {english: "In my view", french: "À mon avis"},
            {english: "From my perspective", french: "De mon point de vue"},
        
    ];

    const portugueseWords = [
        { word: "praia", translation: "plage" },
        { word: "férias", translation: "vacances" },
        { word: "família", translation: "famille" },
        { word: "sol", translation: "soleil" },
        { word: "mar", translation: "mer" },
        { word: "areia", translation: "sable" },
        { word: "guarda-sol", translation: "parasol" },
        { word: "toalha", translation: "serviette" },
        { word: "chapéu", translation: "chapeau" },
        { word: "óculos de sol", translation: "lunettes de soleil" },
        { word: "protetor solar", translation: "crème solaire" },
        { word: "nadar", translation: "nager" },
        { word: "mergulhar", translation: "plonger" },
        { word: "surfar", translation: "surfer" },
        { word: "castelo de areia", translation: "château de sable" },
        { word: "sorvete", translation: "glace" },
        { word: "água de coco", translation: "eau de coco" },
        { word: "caipirinha", translation: "caipirinha" },
        { word: "bronzear", translation: "bronzer" },
        { word: "rede", translation: "hamac" },
        { word: "barco", translation: "bateau" },
        { word: "peixe", translation: "poisson" },
        { word: "frutos do mar", translation: "fruits de mer" },
        { word: "pôr do sol", translation: "coucher du soleil" },
        { word: "lua", translation: "lune" },
        { word: "estrela", translation: "étoile" },
        { word: "viagem", translation: "voyage" },
        { word: "hotel", translation: "hôtel" },
        { word: "pousada", translation: "auberge" },
        { word: "resort", translation: "resort" },
        { word: "turista", translation: "touriste" },
        { word: "guia", translation: "guide" },
        { word: "mapa", translation: "carte" },
        { word: "avião", translation: "avion" },
        { word: "aeroporto", translation: "aéroport" },
        { word: "passaporte", translation: "passeport" },
        { word: "bagagem", translation: "bagage" },
        { word: "malas", translation: "valises" },
        { word: "check-in", translation: "enregistrement" },
        { word: "assento", translation: "siège" },
        { word: "janela", translation: "fenêtre" },
        { word: "corredor", translation: "couloir" },
        { word: "decolagem", translation: "décollage" },
        { word: "pouso", translation: "atterrissage" },
        { word: "turbulência", translation: "turbulence" },
        { word: "comissário de bordo", translation: "hôtesse de l'air" },
        { word: "piloto", translation: "pilote" },
        { word: "capitão", translation: "capitaine" },
        { word: "primeiro oficial", translation: "premier officier" },
        { word: "viagem internacional", translation: "voyage international" },
        { word: "viagem nacional", translation: "voyage national" },
        { word: "visto", translation: "visa" },
        { word: "consulado", translation: "consulat" },
        { word: "embaixada", translation: "ambassade" },
        { word: "turismo", translation: "tourisme" },
        { word: "lazer", translation: "loisirs" },
        { word: "negócios", translation: "affaires" },
        { word: "mochila", translation: "sac à dos" },
        { word: "albergue", translation: "auberge" },
        { word: "hostel", translation: "auberge de jeunesse" },
        { word: "camping", translation: "camping" },
        { word: "trilha", translation: "randonnée" },
        { word: "natureza", translation: "nature" },
        { word: "montanha", translation: "montagne" },
        { word: "rio", translation: "rivière" },
        { word: "lago", translation: "lac" },
        { word: "cachoeira", translation: "cascade" },
        { word: "parque", translation: "parc" },
        { word: "reserva", translation: "réserve" },
        { word: "fauna", translation: "faune" },
        { word: "flora", translation: "flore" },
        { word: "espécie", translation: "espèce" },
        { word: "ecoturismo", translation: "écotourisme" },
        { word: "aventura", translation: "aventure" },
        { word: "esporte", translation: "sport" },
        { word: "radical", translation: "extrême" },
        { word: "parapente", translation: "parapente" },
        { word: "asa-delta", translation: "deltaplane" },
        { word: "escalada", translation: "escalade" },
        { word: "rapel", translation: "rappel" },
        { word: "canoagem", translation: "canoë" },
        { word: "rafting", translation: "rafting" },
        { word: "tirolesa", translation: "tyrolienne" },
        { word: "trilha sonora", translation: "bande sonore" },
        { word: "música", translation: "musique" },
        { word: "filme", translation: "film" },
        { word: "cinema", translation: "cinéma" },
        { word: "série", translation: "série" },
        { word: "episódio", translation: "épisode" },
        { word: "temporada", translation: "saison" },
        { word: "documentário", translation: "documentaire" },
        { word: "comédia", translation: "comédie" },
        { word: "drama", translation: "drame" },
        { word: "ação", translation: "action" },
        { word: "aventura", translation: "aventure" },
        { word: "romance", translation: "romance" },
        { word: "terror", translation: "horreur" },
        { word: "ficção científica", translation: "science-fiction" },
        { word: "fantasia", translation: "fantaisie" },
        { word: "animação", translation: "animation" },
        { word: "curta-metragem", translation: "court-métrage" },
        { word: "longa-metragem", translation: "long métrage" },
        { word: "diretor", translation: "réalisateur" },
        { word: "produtor", translation: "producteur" },
        { word: "roteiro", translation: "scénario" },
        { word: "roteirista", translation: "scénariste" },
        { word: "ator", translation: "acteur" },
        { word: "atriz", translation: "actrice" },
        { word: "elenco", translation: "distribution" },
        { word: "trilha", translation: "piste" }
    ];

    window.displayRandomEnglishWords = function() {
        const randomIndex = Math.floor(Math.random() * englishWords.length);
        const randomWord = englishWords[randomIndex];
        document.getElementById('englishWord').innerHTML = `${randomWord.english} <span class="translation">(${randomWord.french})</span>`;
    };

    window.displayRandomPortugueseWords = function() {
        const randomIndex = Math.floor(Math.random() * portugueseWords.length);
        const randomWord = portugueseWords[randomIndex];
        document.getElementById('portugueseWord').innerHTML = `${randomWord.word} <span class="translation">(${randomWord.translation})</span>`;
    };
});
